namespace SourceGenerator
{
    using System;
    using System.Linq;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp.Syntax;

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 以下をベースに作成している。
    /// cf. https://neue.cc/2022/12/16_IncrementalSourceGenerator.html
    /// </remarks>
    [Generator(LanguageNames.CSharp)]
    public class SampleGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Called to initialize the generator and register generation steps via callbacks
        /// on the <paramref name="context" />
        /// </summary>
        /// <param name="context">The <see cref="T:Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext" /> to register callbacks on</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            //
            context.RegisterPostInitializationOutput(static context =>
            {
                context.AddSource("SampleGeneratedAttribute.g.cs"
                      , @"
namespace CSharp09
{
    using System;

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class GenerateToStringAttribute : Attribute
    {
    }
}
");
            });

            var source = context.SyntaxProvider.ForAttributeWithMetadataName("CSharp09.GenerateToStringAttribute"
                  , static (node,    token) => true
                  , static (context, token) => context);

            context.RegisterSourceOutput(source, Emit);
        }

        private void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
        {
            var typeSymbol = (INamedTypeSymbol) source.TargetSymbol;
            var typeNode   = (TypeDeclarationSyntax) source.TargetNode;

            if (typeSymbol.GetMembers("ToString").Length != 0)
            {
                // すでに ToString() が実装されていれば自動生成できないので、コンパイルエラーにする。
                context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.ExistsOverrideToString
                      , typeNode.Identifier.GetLocation()
                      , typeSymbol.Name));
                return;
            }

            var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
                    ? string.Empty
                    : $"namespace {typeSymbol.ContainingNamespace}";

            var fullType = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                                     .Replace("global::", "")
                                     .Replace("<", "_")
                                     .Replace(">", "_");

            var publicMembers = typeSymbol.GetMembers()
                                          .Where(x => x is (IFieldSymbol or IPropertySymbol)
                                                           and
                                                           {
                                                               IsStatic             : false
                                                             , DeclaredAccessibility: Accessibility.Public
                                                             , IsImplicitlyDeclared : false
                                                             , CanBeReferencedByName: true
                                                           })
                                          .Select(x => $"{x.Name}:{{{x.Name}}}");

            var toString = string.Join(", ", publicMembers);

            var code = $"// <auto-generated/>\r\n"
                     + $"#nullable enable\r\n\r\n"
                     + $"{ns}\r\n"
                     + $"{{\r\n"
                     + $"    partial class {typeSymbol.Name}\r\n"
                     + $"    {{\r\n"
                     + $"        public override string ToString()\r\n"
                     + $"        {{\r\n"
                     + $"            return $\"{toString}\";\r\n"
                     + $"        }}\r\n"
                     + $"    }}\r\n"
                     + $"}}\r\n";

            context.AddSource($"{fullType}.SampleGenerator.g.cs", code);
        }
    }

    public static class DiagnosticDescriptors
    {
        const string Category = "SampleGenerator";

        public static readonly DiagnosticDescriptor ExistsOverrideToString = new(
                id: "SAMPLE001",
                title: "ToString override",
                messageFormat: "The GenerateToString class '{0}' has ToString override but it is not allowed.",
                category: Category,
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true);
    }
}